### ISSUE TITLE
Failing tests with python3

### ISSUE THREAD

**Issue by vvidic** [krig/parallax#3]
The tests all fail with the same problem if started with ``python3 test/test_api.py``.
Is the library supposed to work with python3.5 in this case?

```
EEEE
======================================================================
ERROR: testFailingCall (__main__.CallTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_api.py", line 51, in testFailingCall
    for host, result in para.call(g_hosts, "touch /foofoo/barbar/jfikjfdj", opts).iteritems():
  File "/tmp/autopkgtest-virt-lxc.shared.27v0dztk/downtmp/build.LPI/parallax-1.0.1/parallax/__init__.py", line 159, in call
    callbacks=_CallOutputBuilder())
  File "/tmp/autopkgtest-virt-lxc.shared.27v0dztk/downtmp/build.LPI/parallax-1.0.1/parallax/manager.py", line 78, in __init__
    self.iomap = make_iomap()
  File "/tmp/autopkgtest-virt-lxc.shared.27v0dztk/downtmp/build.LPI/parallax-1.0.1/parallax/manager.py", line 365, in make_iomap
    return PollIOMap()
  File "/tmp/autopkgtest-virt-lxc.shared.27v0dztk/downtmp/build.LPI/parallax-1.0.1/parallax/manager.py", line 319, in __init__
    super(PollIOMap, self).__init__()
  File "/tmp/autopkgtest-virt-lxc.shared.27v0dztk/downtmp/build.LPI/parallax-1.0.1/parallax/manager.py", line 253, in __init__
    signal.set_wakeup_fd(wakeup_writefd)
ValueError: the fd 4 must be in non-blocking mode
```

**Comment by krig** [comment]
It is supposed to work with Python 3.5, but there may certainly be bugs with Python 3..
